### ISSUE TITLE
Not finding this folder chaincode-docker-devmode

### ISSUE THREAD

**Issue by deefstes** [hyperledger/fabric-samples#1064]
### Discussed in https://github.com/hyperledger/fabric-samples/discussions/824

<div type='discussions-op-text'>

<sup>Originally posted by **aruns05** September  7, 2022</sup>
Hello All

I am going through the below section. it says git clone fabric-samples will also add a folder chaincode-docker-devmode
I am not able to see it, can anyone advise

https://github.com/hyperledger/fabric-contract-api-go/blob/v1.1.1/tutorials/getting-started.md</div>

**Comment by deefstes** [comment]
I've created this issue from the discussion as I ran into the same problem going through the latest version (v1.2.1) of the getting started guide.

**Comment by bestbeforetoday** [comment]
The chaincode-docker-devmode sample was removed but can still be found in the [release-1.4](https://github.com/hyperledger/fabric-samples/tree/release-1.4/chaincode-docker-devmode) branch. I doubt it works with current Fabric versions.

Issue hyperledger/fabric-contract-api-go#60 tracks the out-of-date tutorial content in that repository. Probably the current [test-network](https://github.com/hyperledger/fabric-samples/tree/main/test-network) should be used to deploy the tutorial chaincode. For rapid delopment, chaincode-as-a-service should be used instead of the legacy devmode, as demonstrated in the [full-stack-asset-transfer-guide](https://github.com/hyperledger/fabric-samples/tree/main/full-stack-asset-transfer-guide) sample.
