### ISSUE TITLE
Can I use networks other than test-network for commercial purposes?

### ISSUE THREAD

**Issue by aectarine** [hyperledger/fabric-samples#1071]
Is the commercial paper no longer available? How to create a production network?

**Comment by bestbeforetoday** [comment]
The Commercial Paper sample can be found in the [release-2.2](https://github.com/hyperledger/fabric-samples/tree/release-2.2/commercial-paper) branch. Since it uses legacy SDKs that are no longer supported with current Fabric releases, I recommend that you use samples in the main branch as a reference for how to build client applications. The chaincode and general information in the Commercial Paper sample may still be useful.

The Fabric documentation includes some guidance on best-practice for [deploying a production network](https://hyperledger-fabric.readthedocs.io/en/latest/deployment_guide_overview.html).
