### ISSUE TITLE
the laster version run application-go/assetTransfer.go error

### ISSUE THREAD

**Issue by larryhq** [hyperledger/fabric-samples#1078]
I download the main branch code to localhost, when I run fabric-samples/asset-transfer-basic/application-go/assetTransfer.go traceback error
 [fabsdk/util] 2023/07/27 07:58:28 UTC - lazyref.(*Reference).refreshValue -> WARN Error - initializer returned error: load MSPs from config failed: configure MSP failed: sanitizeCert failed the supplied identity is not valid: x509: certificate signed by unknown authority. Will retry again later
2023/07/27 15:58:28 Failed to Submit transaction: Failed to submit: Discovery status Code: (11) UNKNOWN. Description: error getting endorsers: no endorsement combination can be satisfied
exit status 1
my golang version is go1.20.6
run pass through gateway is ok!
why this? Is this code BUG?

**Comment by larryhq** [comment]
my fabric-ca version 1.5.6

**Comment by bestbeforetoday** [comment]
The [legacy Go SDK](https://github.com/hyperledger/fabric-sdk-go) is no longer supported and the accompanying sample client application has been replaced by one using the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/), which is the recommended and only supported client API for Fabric v2.5. Since this issue relates to the legacy SDK and won't be addressed, I am going to close it.
