### ISSUE TITLE
incomplete doc for Asset-Transfer-Basic as an external service

### ISSUE THREAD

**Issue by hbakhtiyor** [hyperledger/fabric-samples#1137]
https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/chaincode-external/README.md

when run this command, getting error

```
setGlobals 1
peer lifecycle chaincode install ../asset-transfer-basic/chaincode-external/asset-transfer-basic-external.tgz
```

```
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: platform builder failed: Failed to generate a Dockerfile: Unknown chaincodeType: EXTERNAL
```

**Comment by satota2** [comment]
@hbakhtiyor
Based on the error, it seems that the expected external chaincode builder does not work correctly, and instead, the default internal  chaincode builder is being used.

You need to set up a Fabric network with the external-sample-builder according to the steps in the doc, and it's possible that this hasn't been done correctly.
Could you please recheck and rerun the instructions in [Setting up the external builder and launcher](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/chaincode-external/README.md#setting-up-the-external-builder-and-launcher)?
This could resolve the issue.

**Comment by juncaluriol** [comment]
@satota2 @hbakhtiyor 

I am trying to implement the external chaincode builder using [Asset-Transfer-Basic as an external service](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/chaincode-external/README.md#asset-transfer-basic-as-an-external-service) but I get the same error when I execute:

`peer lifecycle chaincode install ../asset-transfer-basic/chaincode-external/asset-transfer-basic-external.tgz`

`Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: platform builder failed: Failed to generate a Dockerfile: Unknown chaincodeType: EXTERNAL`

I have follow step by step the tutorial guide but I am not able to implement the external builder

**Comment by satota2** [comment]
@juncaluriol 
I've confirmed the situation.

It seems that `fabric-samples/config/core.yaml` is currently not being read by the Docker peer containers in the test-network. Please modify `fabric-samples/test-network/compose/docker/peercfg/core.yaml` instead.

As discussed in the following mailing list exchange, starting with Fabric v2.5, you need to change the scripts (detect, build, release, run) to start with `#!/bin/bash` instead of `#!/bin/sh`. Please modify files in `chaincode-external/sampleBuilder/bin`.
https://lists.hyperledger.org/g/fabric/topic/104464487

Please try these modifications and retry.

Additionally, I plan to submit a patch to fix the bugs in the procedures I've identified above.
