### ISSUE TITLE
Error while execute chaincode query 

### ISSUE THREAD

**Issue by hirenamnex** [hyperledger/fabric-samples#1142]
When I hit below command I got error : 

**Command :**  peer chaincode query -C mychannel -n basic -c '{"Args":["GetAllAssets"]}'
**Error:**   Fatal error when initializing core config : error when reading core config file: Config File "core" Not Found in "[/home/ispladmin/hiren/hyperledger/fabric-samples/test-network]"

**Comment by satota2** [comment]
@hirenamnex 
It appears that this error is occurring because the environment variable for the config file path has not been set correctly.
If you are following the steps in [test-network tutorial](https://hyperledger-fabric.readthedocs.io/en/latest/test_network.html), I believe you can resolve this error by executing the following environment variable setting command mentioned in [the tutorial](https://hyperledger-fabric.readthedocs.io/en/latest/test_network.html#interacting-with-the-network):

```sh
export FABRIC_CFG_PATH=$PWD/../config/
```
