### ISSUE TITLE
I'm unable to start mt fabric network. Error msg - 

### ISSUE THREAD

**Issue by osemuaimiosior** [hyperledger/fabric-samples#1256]
I get this error msg: Peer binary and configuration files not found..

I have installed the docker binaries and clone the fabric repo as seen in the image, pls i'm not sure what I'm doing wrong, thanks.

<img width="958" alt="Screenshot 2024-10-06 003301" src="https://github.com/user-attachments/assets/bb3d87b4-6e29-47e4-be5a-6f1cc85a76da">

Below i tried to start up the network, i get an error message.

<img width="775" alt="Screenshot 2024-10-11 110345" src="https://github.com/user-attachments/assets/8ef125b5-2a4c-4ed4-8d0e-299056eaf421">

**Comment by bestbeforetoday** [comment]
It looks like you might not have Docker properly installed or running on your machine. Since the download of the Docker images failed, the install script did not proceed to download the Fabric binaries and configuration. Without these you cannot start the test network.

Not the prerequisites in the Fabric documentation:

https://hyperledger-fabric.readthedocs.io/en/latest/prereqs.html

If you are using a Windows environment, I would strongly recommend installing Windows Subsystem for Linux (WSL2) and installing everything (including Docker) there using the instructions for a Linux (Ubuntu) environment.
