### ISSUE TITLE
Error msg while trying to create a channel with "./network.sh createChannel"

### ISSUE THREAD

**Issue by osemuaimiosior** [hyperledger/fabric-samples#1257]
I first of used this command to start up the network, which worked.

`./network.sh up.`

then i tried creating a channel using this command

`./network.sh createChannel`

attached is an image of the error message I get after typing in the above command for channel creation.

<img width="839" alt="Screenshot 2024-10-12 000405" src="https://github.com/user-attachments/assets/7f25ed4b-76b9-4b9f-867d-211e3f098f58">

also, I am using WSL ubuntun on my VScode too

<img width="218" alt="Screenshot 2024-10-11 184624" src="https://github.com/user-attachments/assets/59106fd4-ae56-4c0a-80db-39ebd510eede">

**Comment by osemuaimiosior** [comment]
Tried creating  a new self signed tlca certificate to replace the one that came with the test network using OpenSSL, that did not work.

**Comment by bestbeforetoday** [comment]
I have seen similar issues because of Docker volumes not being cleaned up from previous attempts, or from the local filesystem containing files left over from previous attempts.

To clean up any incorrect Docker volumes, I suggest:

1. `./network.sh down` (in the test-network directory)
2. `docker system prune --volumes`

To clean up the local filesystem, an option is:

1. `git clean -ffdx` (at the repository root directory)
2. Re-run the Fabric installer for the binaries (at the repository root directory):
    ```bash
    curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s -- binary
    ```

I usually do both.

**Comment by osemuaimiosior** [comment]
I see...

Thanks, this worked.
