### ISSUE TITLE
Chaincode Endorsement Policy using Specific Peer(s)

### ISSUE THREAD

**Issue by manavdeep** [hyperledger/fabric-samples#1265]
Hello
So I wanted to know if it is possible to specify signature policy having specific peers. Something like:
--signature-policy "AND('Org1MSP.peer0.org1', 'Org2MSP.peer0.org2')"

Right now I am using Org wide signature policy like:
--signature-policy "AND('Org1MSP.peer', 'Org2MSP.peer')"

I wanted to restrict it to specific peers. That not possible?

**Comment by bestbeforetoday** [comment]
See the [endorsement policies](https://hyperledger-fabric.readthedocs.io/en/latest/endorsement-policies.html) section of the documentation. If you need to assign different authority to different groups of peers within a single organisation, you could instead place each group of peers in their own organisation.

**Comment by manavdeep** [comment]
So lets say I wanted to add peer0, peer3 and peer5 as mandatory endorsers, I add them in Org1MSP.
Event then specifying  --signature-policy "AND('Org1MSP.peer', 'Org2MSP.peer')" only ensures that "at least one of peer 0,3 and 5" should endorse the transaction. I have no way to mandate endorsement from all of them?

**Comment by bestbeforetoday** [comment]
If you need three specific peers to endorse then I think you would need to put each of those peers in a separate organisation and require endorsement from all three organisations. Be very careful with this approach since it would mean that if any of those peers are offline, no transactions can be successfully submitted. A key point of having endorsing organisations with multiple peers — any one of which can endorse — is that it provides fault tolerance.
