### ISSUE TITLE
Hyperledger Fabric Commercial Paper Tutorial Link canot open 

### ISSUE THREAD

**Issue by JackGod001** [hyperledger/fabric-samples#672]
[Hyperledger Fabric Commercial Paper Tutorial](https://hyperledger-fabric.readthedocs.io/en/latest/tutorial/commercial_paper.html
)
[Documentation page](https://github.com/hyperledger/fabric-samples/tree/main/commercial-paper)
![image](https://user-images.githubusercontent.com/24069576/157482853-9badf8eb-5ab4-4ffd-badf-cff161f290cf.png)

**Comment by joshhus** [comment]
@BaiShaojie123123 

- Where did these broken links ORIGINATE from - please provide so we can remove those links.
- Because the commercial paper tutorial does NOT use the new v2.4 Fabric Gateway service, the commercial paper tutorial docs have been removed in v2.4 (latest) docs. See 2.4 tutorials list here - https://hyperledger-fabric.readthedocs.io/en/latest/tutorials.html
- The commercial paper tutorial docs are still available in v2.3 docs - https://hyperledger-fabric.readthedocs.io/en/release-2.3/tutorial/commercial_paper.html

**Comment by nikhil550** [comment]
There is also a broken link to the developing applications pages from this page: https://hyperledger.github.io/fabric-sdk-node/

**Comment by BaiShaojie123123** [comment]
> 
The link error in this page
[Documentation page](https://github.com/hyperledger/fabric-samples/tree/main/commercial-paper)
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/24069576/184531934-d2ddc873-0e15-46fb-9d50-bdc14dd75a58.png">
