### ISSUE TITLE
Remove test-network-k8s

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric-samples#840]
Remove test-network-k8s in favor of fabric-operator and asset-transfer workshop.

**Comment by satota2** [comment]
Hello @denyeart  @jkneubuh
 
I would like to discuss this topic.
 
I would appreciate if test-network-k8s could remain in fabric-samples.
We believe that test-network-k8s is important and useful for Fabric users as well as fabric-operator based examples, because test-network-k8s is the simplest example of Fabric on K8s that does not use any special CRDs or operators.
 
Could you tell us why you are considering removing it and when you plan to do so?

**Comment by denyeart** [comment]
Ok, if there are fans of test-network-k8s let's keep it around.

**Comment by denyeart** [comment]
@jkneubuh @satota2 The test-network-k8s update to Fabric v2.5 is failing CI - https://github.com/hyperledger/fabric-samples/pull/1033

Are either of you interested in troubleshooting, fixing, and maintaining it going forward? Otherwise we'll plan to remove it and focus maintenance effort on fabric-operator and full-stack-asset-transfer.

**Comment by satota2** [comment]
@denyeart I am interested in troubleshooting, fixing, and maintaining it going forward.
At this time, we believe that test-network-k8s is also a good example for for Fabric users to run Fabric on K8s.
Although eventually fabric-operator or another example may make this unnecessary.

I just checked the cause of this CI failure and it seems that k8s builder executable cannot be executed for some reason.
(I suspect the cause is that the peer pods try to run a Go binary created in Alpine on Ubuntu.)

Since Japan is on vacation this week, I will make and submit patches to fabric-samples and hyperledger-labs/fabric-builder-k8s to resolve this issue in the next week or so.

**Comment by denyeart** [comment]
Thanks @satota2 !

**Comment by satota2** [comment]
@denyeart I submitted a patch to resolve the distribution miss match between k8s builder image and Fabric peer image to fabric-builder-k8s repo.
https://github.com/hyperledger-labs/fabric-builder-k8s/pull/92

I ran test-network-k8s in my local environment with a Docker image based on the above patch and confirmed that it runs successfully. So, the above patch is merged and the image based on it is published, test-network-k8s will be ready for Fabric v2.5 support. If the merge of this patch takes a long period of time or is unacceptable, I will try to fix how to get k8s-builder binaries on the test-network-k8s side.

**Comment by denyeart** [comment]
@jkneubuh @jt-nti Do you intend to continue maintaining fabric-builder-k8s?

**Comment by jt-nti** [comment]
@denyeart Hi, yes, still planning to keep fabric-builder-k8s maintained. I was already planning to update it to Fabric 2.5 - hyperledger-labs/fabric-builder-k8s#90 - which it looks like @satota2 has submitted a PR for 🥇

**Comment by jt-nti** [comment]
I've released [fabric-builder-k8s v0.11.0](https://github.com/hyperledger-labs/fabric-builder-k8s/releases/tag/v0.11.0) which should hopefully help- let me know if there are any problems.

**Comment by satota2** [comment]
@jt-nti Thank you for merging my PR and releasing fabric-builder-k8s v0.11.0!

@denyeart I created and submitted a PR (#1039) to use the latest k8s builder and Fabric v2.5 by enhancing #1033.
The CI including test-network-k8s now seems to pass.
Please confirm #1039.

**Comment by denyeart** [comment]
Thanks @satota2 , I'll close this issue, test-network-k8s lives on!

**Comment by satota2** [comment]
@denyeart Thanks! Please let me know if there is anything I can do to help maintain test-network-k8s😊
