### ISSUE TITLE
UNAVAILABLE: Unable to resolve host peer0.org2.example.com

### ISSUE THREAD

**Issue by Theskiteflyingfordream** [hyperledger/fabric-samples#930]
For the Fabcar case, when I run the application and the docker container in the blockchain network on different hosts, when the application side executes "submitTransaction", the error "Unable to resolve host peer0. org2. example. com, cause=java. lang. RuntimeException: java. net. UnknownHostException: peer0. org2. example. com" will be reported, but when "evaluateTransaction" is executed, the error will not be reported.

It is known that the gateway and other configuration files on the application side have been adjusted, and the discovery.asLocalhost and discovery.enabled have also been adjusted. I guess it is a problem related to service discovery.

Can anyone who has encountered this problem or understands it help solve it?

**Comment by bestbeforetoday** [comment]
It will not be possible to resolve `peer0.org2.example.com` in DNS since `example.com` is a reserved domain for documentation purposes only. Likely there was an configuration issue that meant this address was being resolved in DNS rather than being mapped to a known address in the connection profile or using as-localhost discovery settings in the client.

Regardless, Fabcar is not a currently supported sample. I suggest using a current Fabric version and the [asset-transfer-basic](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic) sample. Also note that the legacy client application SDKs have all been replaced by the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/), which provides a more robust and less error-prone client-side experience.
